map = get_googlemap(center = c(lon = 30.418314, lat = 59.890538), zoom = 12, maptype = "roadmap", scale = 2, style = c("feature:all|element:labels|visibility:off","&style=feature:road|element:geometry|color:0x8A6996|lightness:18|saturation:50|weight:0.2", "&style=feature:landscape|element:geometry|color:0xFAFAFA|lightness:98|saturation:100", "&style=feature:poi|element:geometry|color:0xFAFAFA|lightness:98|saturation:100"))
map13 = map = get_googlemap(center = c(lon = 30.418314, lat = 59.890538), zoom = 13, maptype = "roadmap", scale = 2, style = c("feature:all|element:labels|visibility:off","&style=feature:road|element:geometry|color:0x8A6996|lightness:18|saturation:50|weight:0.2", "&style=feature:landscape|element:geometry|color:0xFAFAFA|lightness:98|saturation:100", "&style=feature:poi|element:geometry|color:0xFAFAFA|lightness:98|saturation:100"))

ggmap(map) + geom_point(aes(x = lon, y = lat), data = map.data[map.data$is.ya == 0,], size = 0.5, color = "black")
#style is awesome! incredible power

#mapping 
#loading extrafonts failed badly: "no fontname" issue?
#for both virtual & real
png("~/sso-physical-disorder-analysis/plots/all.png", width = 2056, height = 2056, units = "px", res = 300)
ggmap(map13) + geom_point(aes(x = lon, y = lat, color = "Virtual & real"), data = map.data[map.data$id %in% intersect(map.data[map.data$is.ya == 1,]$id, map.data[map.data$is.ya == 0,]$id),], size = 0.75) +
              geom_point(aes(x = lon, y = lat, color = "Only virtual"), data = map.data[(map.data$id %in% setdiff(map.data[map.data$is.ya == 1,]$id, map.data[map.data$is.ya == 0,]$id)) & map.data$is.ya == 1,], size = 0.75) +
              geom_point(aes(x = lon, y = lat, color = "Only real"), data = map.data[(map.data$id %in% setdiff(map.data[map.data$is.ya == 0,]$id, map.data[map.data$is.ya == 1,]$id)) & map.data$is.ya == 0,], size = 0.75) + #first - both, second - ya, third - real
              scale_color_manual(values=c("#8DA0CB", "#66C2A5", "#FC8D62"), guide = guide_legend(title = NULL, override.aes = list(size = 6), keywidth=0.2, keyheight=0.26,default.unit="inch")) + theme(axis.line=element_blank(),axis.text.x=element_blank(), axis.text.y=element_blank(),axis.ticks=element_blank(), axis.title.x=element_blank(), axis.title.y=element_blank(), panel.background=element_blank(),panel.border=element_blank(),panel.grid.major=element_blank(),panel.grid.minor=element_blank(),plot.background=element_blank(), 
                                                                                                                                                                                                          legend.text = element_text(size=14), legend.position = c(0.29, 0.02), legend.background = element_rect(fill = rgb(0.99, 0.99, 0.99, 0.7)), legend.key = element_blank(), legend.direction = "horizontal")
dev.off()
#for both virtual & real
png("~/sso-physical-disorder-analysis/plots/all-less-zoom.png", width = 2056, height = 2056, units = "px", res = 300)
ggmap(map) + geom_point(aes(x = lon, y = lat, color = "Virtual & real"), data = map.data[map.data$id %in% intersect(map.data[map.data$is.ya == 1,]$id, map.data[map.data$is.ya == 0,]$id),], size = 0.75) +
  geom_point(aes(x = lon, y = lat, color = "Only virtual"), data = map.data[(map.data$id %in% setdiff(map.data[map.data$is.ya == 1,]$id, map.data[map.data$is.ya == 0,]$id)) & map.data$is.ya == 1,], size = 0.75) +
  geom_point(aes(x = lon, y = lat, color = "Only real"), data = map.data[(map.data$id %in% setdiff(map.data[map.data$is.ya == 0,]$id, map.data[map.data$is.ya == 1,]$id)) & map.data$is.ya == 0,], size = 0.75) + #first - both, second - ya, third - real
  scale_color_manual(values=c("#8DA0CB", "#66C2A5", "#FC8D62"), guide = guide_legend(title = NULL, override.aes = list(size = 6), keywidth=0.2, keyheight=0.26,default.unit="inch")) + theme(axis.line=element_blank(),axis.text.x=element_blank(), axis.text.y=element_blank(),axis.ticks=element_blank(), axis.title.x=element_blank(), axis.title.y=element_blank(), panel.background=element_blank(),panel.border=element_blank(),panel.grid.major=element_blank(),panel.grid.minor=element_blank(),plot.background=element_blank(), 
                                                                                                                                                                                             legend.text = element_text(size=14), legend.position = c(0.29, 0.02), legend.background = element_rect(fill = rgb(0.99, 0.99, 0.99, 0.7)), legend.key = element_blank(), legend.direction = "horizontal")
dev.off()
#just virtual, 2 zooms
png("~/sso-physical-disorder-analysis/plots/virtual.png", width = 2056, height = 2056, units = "px", res = 300)
ggmap(map13) +   geom_point(aes(x = lon, y = lat, color = "Only virtual"), data = map.data[(map.data$id %in% setdiff(map.data[map.data$is.ya == 1,]$id, map.data[map.data$is.ya == 0,]$id)) & map.data$is.ya == 1,], size = 0.75) +
  scale_color_manual(values=c("#66C2A5"), guide = guide_legend(title = NULL, override.aes = list(size = 6), keywidth=0.2, keyheight=0.26,default.unit="inch")) + theme(axis.line=element_blank(),axis.text.x=element_blank(), axis.text.y=element_blank(),axis.ticks=element_blank(), axis.title.x=element_blank(), axis.title.y=element_blank(), panel.background=element_blank(),panel.border=element_blank(),panel.grid.major=element_blank(),panel.grid.minor=element_blank(),plot.background=element_blank(), 
                                                                                                                                                                                             legend.text = element_text(size=14), legend.position = c(0.29, 0.02), legend.background = element_rect(fill = rgb(0.99, 0.99, 0.99, 0.7)), legend.key = element_blank(), legend.direction = "horizontal")
dev.off()
png("~/sso-physical-disorder-analysis/plots/virtual-less-zoom.png", width = 2056, height = 2056, units = "px", res = 300)
ggmap(map) +   geom_point(aes(x = lon, y = lat, color = "Only virtual"), data = map.data[(map.data$id %in% setdiff(map.data[map.data$is.ya == 1,]$id, map.data[map.data$is.ya == 0,]$id)) & map.data$is.ya == 1,], size = 0.75) +
  scale_color_manual(values=c("#66C2A5"), guide = guide_legend(title = NULL, override.aes = list(size = 6), keywidth=0.2, keyheight=0.26,default.unit="inch")) + theme(axis.line=element_blank(),axis.text.x=element_blank(), axis.text.y=element_blank(),axis.ticks=element_blank(), axis.title.x=element_blank(), axis.title.y=element_blank(), panel.background=element_blank(),panel.border=element_blank(),panel.grid.major=element_blank(),panel.grid.minor=element_blank(),plot.background=element_blank(), 
                                                                                                                                                                       legend.text = element_text(size=14), legend.position = c(0.29, 0.02), legend.background = element_rect(fill = rgb(0.99, 0.99, 0.99, 0.7)), legend.key = element_blank(), legend.direction = "horizontal")
dev.off()
#just real, 2 zooms
png("~/sso-physical-disorder-analysis/plots/real-less-zoom.png", width = 2056, height = 2056, units = "px", res = 300)
ggmap(map) +  geom_point(aes(x = lon, y = lat, color = "Only real"), data = map.data[(map.data$id %in% setdiff(map.data[map.data$is.ya == 0,]$id, map.data[map.data$is.ya == 1,]$id)) & map.data$is.ya == 0,], size = 0.75) + #first - both, second - ya, third - real
  scale_color_manual(values=c("#8DA0CB"), guide = guide_legend(title = NULL, override.aes = list(size = 6), keywidth=0.2, keyheight=0.26,default.unit="inch")) + theme(axis.line=element_blank(),axis.text.x=element_blank(), axis.text.y=element_blank(),axis.ticks=element_blank(), axis.title.x=element_blank(), axis.title.y=element_blank(), panel.background=element_blank(),panel.border=element_blank(),panel.grid.major=element_blank(),panel.grid.minor=element_blank(),plot.background=element_blank(), 
                                                                                                                                                                                             legend.text = element_text(size=14), legend.position = c(0.29, 0.02), legend.background = element_rect(fill = rgb(0.99, 0.99, 0.99, 0.7)), legend.key = element_blank(), legend.direction = "horizontal")
dev.off()
png("~/sso-physical-disorder-analysis/plots/real.png", width = 2056, height = 2056, units = "px", res = 300)
ggmap(map13) +  geom_point(aes(x = lon, y = lat, color = "Only real"), data = map.data[(map.data$id %in% setdiff(map.data[map.data$is.ya == 0,]$id, map.data[map.data$is.ya == 1,]$id)) & map.data$is.ya == 0,], size = 0.75) + #first - both, second - ya, third - real
  scale_color_manual(values=c("#8DA0CB"), guide = guide_legend(title = NULL, override.aes = list(size = 6), keywidth=0.2, keyheight=0.26,default.unit="inch")) + theme(axis.line=element_blank(),axis.text.x=element_blank(), axis.text.y=element_blank(),axis.ticks=element_blank(), axis.title.x=element_blank(), axis.title.y=element_blank(), panel.background=element_blank(),panel.border=element_blank(),panel.grid.major=element_blank(),panel.grid.minor=element_blank(),plot.background=element_blank(), 
                                                                                                                                                                       legend.text = element_text(size=14), legend.position = c(0.29, 0.02), legend.background = element_rect(fill = rgb(0.99, 0.99, 0.99, 0.7)), legend.key = element_blank(), legend.direction = "horizontal")
dev.off()
